### ISSUE TITLE
[Epic] Resizetizer Documentation Improvements

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno.resizetizer#265]
- [ ] https://github.com/unoplatform/uno.resizetizer/issues/260
- [ ] https://github.com/unoplatform/uno.resizetizer/issues/262
- [ ] https://github.com/unoplatform/uno.resizetizer/issues/261
- [ ] https://github.com/unoplatform/uno.resizetizer/issues/239

**Comment by agneszitte** [comment]
fyi @dansiegel, @MartinZikmund, @kazo0 
I created this Epic issue to better track the doc improvements we need to do for Resizetizer
